---
home: https://github.com/explorium-ai/kube-proximage
keywords:
  - mutating
  - webhook
  - container
  - image
  - proxy
sources:
  - https://github.com/explorium-ai/kube-proximage
annotations:
  category: Kubernetes
apiVersion: v2
appVersion: "1.0"
description: A Mutating Webhook for Automatic Image Container Proxies
maintainers:
  - name: jatalocks
    url: https://github.com/jatalocks
name: kube-proximage
version: 0.0.1
